;;; -*- Lisp -*-

(defpackage "CHATBOT"
  (:shadowing-import-from "FUNCTION" "COMPOSE")
  (:shadowing-import-from "NAMED-LET" "LET" "NAMED-LAMBDA")
  (:shadowing-import-from "SERIES" "DEFUN" "FUNCALL" "LET*" "MULTIPLE-VALUE-BIND")
  (:use "ALEXANDRIA" "CL" "FOLD" "FUNCTION" "JSONX" "NAMED-LET" "PROMISE" "SERIES" "TRIVIAL-TIMEOUT")
  (:export "CHAT"
           "BUILD-PERSONA-SYSTEM-INSTRUCTION"
           "MAKE-ROUND-ROBIN-PARTICIPANT"
           "NEW-ROUND-ROBIN-CHAT"
           "SPAWN-PERSONA"
           "MAKE-PERSONA-REGISTRY"
           "DEFPERSONA"
           "FIND-PERSONA"
           "LIST-PERSONAS"
           "SHOW-PERSONAS"
           "REMOVE-PERSONA"
           "RESET-PERSONA"
           "RESET-ALL-PERSONAS"
           "CLEAR-PERSONAS"
           "LIST-STOCK-PERSONAS"
           "SPAWN-STOCK-PERSONA"
           "QUERY-ALL"
           "RUN-ARENA"
           "ROUND-ROBIN-CHAT"
           "SEND-LATEST-SCREENSHOT"
           "LISP-NEWS"
           "MAKE-RUNTIME-CONTEXT"
           "NEW-CHAT"
           "NEW-CHAT-PERSONA"
           "SAVE-MINION-STATE"
           "PRUNE-CONVERSATION-CONTEXT-IF-NEEDED"
           "RESTORE-MINIONS"
           "MINIONS-DATA-DIRECTORY"
           "RUN-ALL-TESTS"
           "START-AGENTIC-LOOP"
           "LIST-AGENTIC-LOOPS"
           "FIND-AGENTIC-LOOP"
           "ABORT-AGENTIC-LOOP"
           "ABORT-AGENTIC-LOOPS"
           "RESUME-AGENTIC-LOOP"
           "SAMPLING-PARAMETERS"
           "SET-SAMPLING-PARAMETERS"
           "RESET-SAMPLING-PARAMETERS"
           "SYSTEM-INSTRUCTION-PARAGRAPH-COUNT"
           "SYSTEM-INSTRUCTION-PARAGRAPHS-COPY"
           "SYSTEM-INSTRUCTION-PARAGRAPH"
           "INSERT-SYSTEM-INSTRUCTION-PARAGRAPH"
           "UPDATE-SYSTEM-INSTRUCTION-PARAGRAPH"
           "DELETE-SYSTEM-INSTRUCTION-PARAGRAPH"
           "CLEAR-SYSTEM-INSTRUCTION-PARAGRAPHS"
           "REPLACE-SYSTEM-INSTRUCTION-PARAGRAPHS"
           "SAVE-SYSTEM-INSTRUCTIONS"
           "SAVE-COMPRESSED-PERSONA-MEMORY"
           "INITIALIZE-STARTUP-CHATBOT"
           "STARTUP-CHATBOT-INITIALIZED-P"
           "STARTUP-CHATBOT-MCP-STATUS"
           "LOG-MESSAGE"
           "SHUTDOWN-CHATBOT"
           ;; Compatibility-only ambient runtime globals. Prefer
           ;; MAKE-RUNTIME-CONTEXT plus explicit :RUNTIME-CONTEXT arguments.
           "*WARN-ON-LEGACY-RUNTIME-GLOBALS-P*"
           "*BYPASS-EVAL-APPROVAL-P*"
           "*CONTEXT-PRUNING-THRESHOLD-CHARACTERS*"
           "*MCP-CONFIG-PATH*"
           "*MCP-DEBUG-P*"
           "*AUTO-INITIALIZE-STARTUP-MCP-SERVERS-P*"
           "*DEFAULT-CONVERSATION*"
           "*AGENTIC-LOOP-DEFAULT-BACKEND*"
           "*AGENTIC-LOOP-DEFAULT-MODEL*"
           "*LOGGING-ENABLED-P*"
           "*LOG-LEVEL*"
           "*LOG-STREAM*"
           "*HTTP-CONNECT-TIMEOUT*"
           "*HTTP-READ-TIMEOUT*"
           "*BACKEND-DEFAULT-MODELS*"
           "BACKEND-DEFAULT-MODEL"
           "*GEMINI-BASE-URL*"
           "*GEMINI-API-REVISION*"
           "*OPENAI-BASE-URL*"
           "*OPENAI-API-KEY*"
           "OPENAI-API-KEY"
           "*LM-STUDIO-BASE-URL*"
           "*LM-STUDIO-DEFAULT-API-KEY*"
           "*LM-STUDIO-API-KEY*"
           "LM-STUDIO-API-KEY"
           "*SCREENSHOT-PATH*"
           "*SCREENSHOT-PATH-1*"
           "*SCREENSHOT-PROMPT*"))
